#!/usr/bin/env python3
"""One-time git + ledger setup for a kaggle_solver run (deterministic — no LLM).

Port of mle-beast's GitSetupNode, in the style of lewm's setup_experiment.py.
Runs with cwd = the workspace (after prepare_comp.py has staged data/task.md).

  1. git-init the workspace if needed (fresh dirs on remote nodes),
  2. adds run-artifact patterns to .git/info/exclude so `git add -A` /
     `git clean -fd` in keep_or_revert never touch the data link, checkpoints,
     or the experiment ledger,
  3. switches to (or creates) the experiment branch and commits a snapshot,
  4. seeds research_log.md with the context the proposer needs.

Prints `SETUP=ok BRANCH=<name>` on success.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

DEFAULT_BRANCH = "saage-kaggle"

# Heavy/generated artifacts inside the working tree. .git/info/exclude (not
# .gitignore) so the workspace's own files are never touched by the flow.
EXCLUDES = [
    "data",              # symlink (or copy) of the competition data
    "checkpoints/",
    "logs/",
    "__pycache__/",
    ".venv/",
    "experiments.jsonl",
    "proposals/",
    "task.md",           # regenerated by prepare_comp.py
    "submission.csv",    # regenerated by predict.py; pinned by the final commit
]

LOG_HEADER = """# {comp} — kaggle solver research log

Goal: best {metric} on the held-out test split ({direction} is better).
Submission contract: submission.csv, columns/rows must match
sample_submission.csv exactly.

Budget: every hill-climb experiment trains exactly {short_epochs} epochs
(ShortTrain) so scores are comparable; the final winner re-trains at
{final_epochs} epochs (FinalTrain) before predict + submit.
The validation score that drives keep/revert comes from eval_results.json
written by train.py — never from log prose.

Every experiment below is recorded by keep_or_revert.py.
`keep` = improved the best validation score (committed); `revert` = did not.

## Experiments
"""


def sh(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(args, capture_output=True, text=True)


def git(*args: str) -> subprocess.CompletedProcess:
    return sh("git", "-c", "user.email=saage@local", "-c", "user.name=saage", *args)


def main() -> None:
    ap = argparse.ArgumentParser(allow_abbrev=False)
    ap.add_argument("--comp", required=True)
    ap.add_argument("--metric", default="the competition metric")
    ap.add_argument("--lower-is-better", default="false")
    ap.add_argument("--short-epochs", type=int, default=15)
    ap.add_argument("--final-epochs", type=int, default=100)
    ap.add_argument("--branch", default=DEFAULT_BRANCH,
                    help="experiment branch (remote runs pass the run branch)")
    args = ap.parse_args()
    branch = args.branch or DEFAULT_BRANCH    # templated arg may render empty

    if not Path("task.md").exists():
        print("ERROR: task.md missing — run prepare_comp.py first", file=sys.stderr)
        sys.exit(1)

    if not Path(".git").exists():
        if git("init", "-q").returncode != 0:
            print("ERROR: git init failed", file=sys.stderr)
            sys.exit(1)

    exclude = Path(".git/info/exclude")
    existing = exclude.read_text() if exclude.exists() else ""
    with exclude.open("a") as f:
        for pat in EXCLUDES:
            if pat not in existing:
                f.write(pat + "\n")

    current = sh("git", "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
    if current != branch:
        exists = sh("git", "rev-parse", "--verify", "--quiet", branch).returncode == 0
        r = git("checkout", "-q", branch) if exists else git("checkout", "-q", "-b", branch)
        if r.returncode != 0:
            print(f"ERROR: could not switch to {branch}: {r.stderr}", file=sys.stderr)
            sys.exit(1)

    # Reset the ledger so each run starts clean. research_log.md / experiments.jsonl
    # are git-excluded and persist on a REUSED workspace, so a prior run's rows would
    # otherwise concatenate into this run's report AND the proposer's context (the
    # non-monotonic "best"). setup is a one-shot top-level step; a resumed run
    # re-enters at a later step, so its in-progress ledger is preserved.
    direction = "lower" if str(args.lower_is_better).lower() == "true" else "higher"
    Path("research_log.md").write_text(LOG_HEADER.format(
        comp=args.comp, metric=args.metric, direction=direction,
        short_epochs=args.short_epochs, final_epochs=args.final_epochs))
    Path("experiments.jsonl").unlink(missing_ok=True)

    git("add", "-A")
    git("commit", "-q", "-m", "saage: kaggle solver setup snapshot")

    print(f"SETUP=ok BRANCH={branch}")


if __name__ == "__main__":
    main()
