"""Provision a node once: content-keyed, locked, stamped — H6.

A *provision* is a setup command whose effects live in the node's shared
cache (``$SAAGE_CACHE = ~/.saage_cache``): dataset pulls, ML venvs, repo
mirrors. It is keyed by its content (default: hash of the command), guarded
by a flock (concurrent callers wait, never duplicate work), and stamped on
success — so re-provisioning a node is always safe and a *replacement* box
needs no special recovery path: no stamp, so it provisions cold, exactly
like a first-time node.

Per-run mutable state stays in ``~/.saage_runs/<run_id>/`` and is not
touched here.
"""
from __future__ import annotations

import hashlib
import logging
import shlex
from pathlib import Path

from .creds import Target, storage_config
from .target import SshTarget

log = logging.getLogger("saage.remote")


class ProvisionError(RuntimeError):
    pass


def provision_key(command: str) -> str:
    """Stable content key for a provision command."""
    return hashlib.sha256(command.encode()).hexdigest()[:12]


def _provision_script(command: str, key: str, *, force: bool) -> str:
    drop_stamp = f'rm -f "$SAAGE_CACHE/.stamps/{key}.ready"\n' if force else ""
    return f"""#!/usr/bin/env bash
# generated by saage remote provision — key {key}
set -euo pipefail
export PATH="$HOME/.local/bin:$PATH"
export SAAGE_CACHE="$HOME/.saage_cache"
mkdir -p "$SAAGE_CACHE/.locks" "$SAAGE_CACHE/.stamps" \\
         "$SAAGE_CACHE/provision/{key}"
[ -f "$SAAGE_CACHE/provision/{key}/env" ] && {{
  set -a; source "$SAAGE_CACHE/provision/{key}/env"; set +a; }}
{drop_stamp}exec 9> "$SAAGE_CACHE/.locks/{key}.lock"
flock 9            # concurrent callers wait here; first one does the work
if [ -f "$SAAGE_CACHE/.stamps/{key}.ready" ]; then
  echo PROVISION_CACHED
  exit 0
fi
cd "$SAAGE_CACHE/provision/{key}"
{command}
touch "$SAAGE_CACHE/.stamps/{key}.ready"
echo PROVISION_OK
"""


def provision_node(target: Target, command: str, *, key: str | None = None,
                   files: Path | None = None, env: dict[str, str] | None = None,
                   with_storage_env: bool = True, timeout: int = 3600,
                   force: bool = False) -> str:
    """Run a one-time setup command on a node; returns "ok" or "cached".

    - runs with cwd ``$SAAGE_CACHE/provision/<key>/`` and ``$SAAGE_CACHE``
      exported; the command's job is to populate cache entries
      (``$SAAGE_CACHE/datasets/...``, ``$SAAGE_CACHE/venvs/...``).
    - ``files``: a local dir rsynced to ``./files/`` inside the provision
      cwd first (setup scripts, requirement files, staged datasets).
    - ``env``: extra env for the command; storage (R2) credentials are
      included by default so dataset pulls from the bucket just work. The
      env file is removed after the attempt — secrets never persist.
    - idempotent per ``key`` (default: hash of the command); ``force`` drops
      the stamp first. Concurrent calls for one key serialize on a node-side
      flock — K cold bootstraps = one pull + K-1 cheap waits.
    """
    key = key or provision_key(command)
    node = SshTarget(target)
    conn = node.conn
    pdir = f".saage_cache/provision/{key}"
    conn.run(f"mkdir -p $HOME/{pdir}")
    if files is not None:
        # into ./files/, NOT the cwd root — the cwd also briefly holds the
        # env file (secrets) and provision.sh, which a `cp -r` of staged
        # data must never sweep up
        conn.rsync_to(Path(files).as_posix() + "/", f"{pdir}/files/",
                      excludes=("__pycache__", ".git"))
    env_vars = dict(env or {})
    if with_storage_env:
        storage = storage_config()
        if storage:
            env_vars.setdefault("AWS_ACCESS_KEY_ID", storage.access_key)
            env_vars.setdefault("AWS_SECRET_ACCESS_KEY", storage.secret_key)
            env_vars.setdefault("SAAGE_R2_ENDPOINT", storage.endpoint)
            env_vars.setdefault("SAAGE_R2_BUCKET", storage.bucket)
    if env_vars:
        conn.write_file(f"{pdir}/env", "".join(
            f"{k}={shlex.quote(v)}\n" for k, v in env_vars.items()))
    conn.write_file(f"{pdir}/provision.sh",
                    _provision_script(command, key, force=force), mode="700")
    try:
        proc = conn.run(f"bash $HOME/{pdir}/provision.sh",
                        timeout=timeout, check=False)
    finally:
        conn.run(f"rm -f $HOME/{pdir}/env", check=False)
    out = proc.stdout + proc.stderr
    if "PROVISION_CACHED" in proc.stdout:
        log.info("provision %s on %s: cached", key, target.name)
        return "cached"
    if proc.returncode != 0 or "PROVISION_OK" not in proc.stdout:
        raise ProvisionError(
            f"provision {key} on {target.name!r} failed "
            f"(rc={proc.returncode}):\n{out[-2000:]}")
    log.info("provision %s on %s: ok", key, target.name)
    return "ok"
