"""Generate the three node-side scripts: bootstrap.sh, start.sh, stop.sh.

Conventions on the node (everything per-run, nothing shared between runs):

    ~/.saage_runs/<run_id>/
      saage/        engine source (rsynced from the local checkout)
      venv/         engine virtualenv
      flow/         the flow dir (flow.yaml + skills + helpers)
      ws/           workspace (cloned run branch / bundle, or fresh dir)
      ws.bundle     only in bundle mode
      run_env       per-run secrets, 0600, deleted when the run stops
      artifacts/    the "bucket": ledgers/results copied here by the sidecar;
                    `saage remote fetch` rsyncs this dir back
      status.json   {"phase": ..., "rc": ..., "updated": ...} heartbeat
      saage.log     engine output

The watchdog stops the RUN, never the box — v1 does not own machines.
"""
from __future__ import annotations

import shlex
from dataclasses import dataclass, field

# default sidecar collect list: workspace files copied into artifacts/ — run
# ledgers and results, which are deliberately .gitignored (they can't travel
# via the run branch). A flow with its own naming declares `artifacts:` in
# flow.yaml (a list of filenames/globs, relative to the workspace) instead.
ARTIFACT_FILES = ("experiments.jsonl", "research_log.md", "eval_results.json",
                  "report.html", "report_narrative.md")


@dataclass
class RunSpec:
    run_id: str
    flow_file: str                      # filename inside flow/, e.g. "flow.yaml"
    ws_mode: str                        # 'ephemeral' | 'branch' | 'bundle'
    set_args: dict = field(default_factory=dict)     # --set k=v passthrough
    venv_arg: str | None = None                      # --venv passthrough
    sync_interval: int = 300
    max_run_days: float = 12.0
    r2: bool = False                                 # mirror artifacts to R2/S3
    ws_setup: str | None = None                      # one-time env/data setup, run in ws/
    artifacts: tuple[str, ...] = ARTIFACT_FILES      # flow.yaml `artifacts:` override

    @property
    def run_dir(self) -> str:           # as a remote shell expression
        return f"$HOME/.saage_runs/{self.run_id}"

    @property
    def session(self) -> str:
        return f"saage-{self.run_id}"


def _collect_fn(spec: RunSpec) -> str:
    files = " ".join(spec.artifacts)
    return f"""collect() {{  # the artifacts/ dir is the run's local "bucket"
  for pat in {files}; do
    for f in ws/$pat; do                 # unquoted: patterns may be globs
      [ -f "$f" ] || continue
      dst="artifacts/$(basename "$f")"
      [ -f "$dst" ] && [ ! "$f" -nt "$dst" ] && continue   # unchanged -> skip
      cp -f "$f" "$dst" 2>/dev/null
    done
  done
  # branch mode: push kept commits out on every sync, so a node death loses at
  # most one interval of commits (auth URL only at push time, never in config)
  [ -n "${{WS_RUN_BRANCH:-}}" ] && ( cd ws && \\
      git push -q "${{WS_REPO_AUTH_URL:-origin}}" "$WS_RUN_BRANCH" 2>/dev/null ) || true
  # mirror to R2 when configured (no-op otherwise); never let it break the run
  [ -n "${{SAAGE_R2_BUCKET:-}}" ] && venv/bin/python -m saage.remote.r2push \\
      >> r2push.log 2>&1 || true
  return 0
}}"""


def _status_fn() -> str:
    return """status() {
  printf '{"phase":"%s","rc":%s,"updated":"%s"}\\n' "$1" "${2:-0}" \\
         "$(date -u +%FT%TZ)" > status.json.tmp
  mv status.json.tmp status.json
}"""


def bootstrap_sh(spec: RunSpec) -> str:
    # clone may use the token-bearing URL (private repos), but the URL that
    # persists in ws/.git/config is always the clean one — see _collect_secrets
    ws_setup = {
        "ephemeral": "mkdir -p ws",
        "branch": '[ -d ws/.git ] || { git clone --quiet --branch "$WS_RUN_BRANCH" '
                  '"${WS_REPO_AUTH_URL:-$WS_REPO_URL}" ws && '
                  'git -C ws remote set-url origin "$WS_REPO_URL"; }',
        "bundle": '[ -d ws/.git ] || git clone --quiet --branch "$WS_RUN_BRANCH" ./ws.bundle ws',
    }[spec.ws_mode]
    boto3 = " boto3" if spec.r2 else ""
    # flow-specific env/data prep (e.g. le-wm's cloud_setup.sh) — runs inside
    # the workspace, with the flow dir reachable at ../flow
    ws_setup_hook = f"( cd ws && {spec.ws_setup} )" if spec.ws_setup else ""
    return f"""#!/usr/bin/env bash
# generated by saage remote handoff — run {spec.run_id}
set -euo pipefail
export PATH="$HOME/.local/bin:$PATH"
cd "{spec.run_dir}"
set -a; source ./run_env; set +a

command -v uv >/dev/null 2>&1 || curl -LsSf https://astral.sh/uv/install.sh | sh
export PATH="$HOME/.local/bin:$PATH"

uv venv venv --quiet
VIRTUAL_ENV="$PWD/venv" uv pip install --quiet -e ./saage{boto3}

mkdir -p artifacts
{ws_setup}
{ws_setup_hook}
echo BOOTSTRAP_OK
"""


def _run_body(spec: RunSpec, engine_line: str, run_branch_flag: str = "") -> str:
    """Shared sidecar/watchdog/status wrapper for start.sh and resume.sh.

    ``engine_line`` is the full ``venv/bin/saage ...`` command (without
    trailing ``> saage.log 2>&1``, which is appended here).

    ``run_branch_flag`` is an optional shell block (multi-line string) that
    is inserted immediately before the ``status running`` / engine lines.
    Pass the empty string (default) when no run-branch flag is needed
    (e.g. resume.sh).
    """
    max_run_seconds = int(spec.max_run_days * 86400)
    # Only emit the block (with a trailing newline) when it is non-empty.
    run_branch_section = f"{run_branch_flag}\n" if run_branch_flag else ""
    return f"""#!/usr/bin/env bash
# generated by saage remote handoff — run {spec.run_id}
set -uo pipefail
export PATH="$HOME/.local/bin:$PATH"
cd "{spec.run_dir}"
set -a; source ./run_env; set +a

{_status_fn()}

{_collect_fn(spec)}

( while true; do status running; collect; sleep {spec.sync_interval}; done ) &
SIDECAR=$!
# watchdog: a wedged run can't hold the box forever — stops the RUN, never the box
( sleep {max_run_seconds} && touch watchdog_fired && pkill -P $$ 2>/dev/null ) &
WATCHDOG=$!

{run_branch_section}status running
{engine_line} > saage.log 2>&1
RC=$?

kill "$SIDECAR" "$WATCHDOG" 2>/dev/null
# final phase FIRST, then collect — so the last mirror push carries it
if [ -f watchdog_fired ]; then status timeout 124
elif [ "$RC" -eq 0 ]; then status done 0
else status failed "$RC"; fi
collect
# final push of kept experiments (collect already pushes every sync interval)
( cd ws && git push -q "${{WS_REPO_AUTH_URL:-origin}}" "${{WS_RUN_BRANCH:-}}" 2>/dev/null ) || true
rm -f run_env            # secrets do not outlive the run
"""


def start_sh(spec: RunSpec) -> str:
    set_flags = " ".join(
        f"--set {shlex.quote(f'{k}={v}')}" for k, v in spec.set_args.items()
    )
    venv_flag = f"--venv {shlex.quote(spec.venv_arg)}" if spec.venv_arg else ""
    # packaged workspace: tell the flow which branch it is on, so flows that manage
    # their own experiment branch (e.g. lewm setup_experiment --branch) commit to
    # the branch the push-back channel actually pushes
    engine = (f'venv/bin/saage run "flow/{spec.flow_file}" --workspace "$PWD/ws" '
              f'{venv_flag} {set_flags} \\\n  $RUN_BRANCH_FLAG')
    run_branch_flag = (
        '# packaged workspace: tell the flow which branch it is on, so flows that manage\n'
        '# their own experiment branch (e.g. lewm setup_experiment --branch) commit to\n'
        '# the branch the push-back channel actually pushes\n'
        'RUN_BRANCH_FLAG=""\n'
        '[ -n "${WS_RUN_BRANCH:-}" ] && RUN_BRANCH_FLAG="--set run_branch=$WS_RUN_BRANCH"'
    )
    return _run_body(spec, engine, run_branch_flag=run_branch_flag)


def resume_sh(spec: RunSpec) -> str:
    """start.sh, but resume the engine from the node-side checkpoint instead of a
    fresh run. SAAGE_RUN_ID comes from run_env (the pinned id)."""
    engine = f'venv/bin/saage resume "$SAAGE_RUN_ID" --workspace "$PWD/ws"'
    return _run_body(spec, engine)


def stop_sh(spec: RunSpec) -> str:
    files = " ".join(spec.artifacts)
    return f"""#!/usr/bin/env bash
# generated by saage remote handoff — run {spec.run_id}
# stop the RUN, never the box
cd "{spec.run_dir}" || exit 0
set -a; source ./run_env 2>/dev/null; set +a    # may already be gone — fine
tmux kill-session -t {shlex.quote(spec.session)} 2>/dev/null || true
mkdir -p artifacts
for pat in {files}; do
  for f in ws/$pat; do                 # unquoted: patterns may be globs
    [ -f "$f" ] && cp -f "$f" artifacts/ 2>/dev/null
  done
done
printf '{{"phase":"killed","rc":137,"updated":"%s"}}\\n' "$(date -u +%FT%TZ)" > status.json
[ -n "${{SAAGE_R2_BUCKET:-}}" ] && venv/bin/python -m saage.remote.r2push \\
    >> r2push.log 2>&1 || true
rm -f run_env
exit 0
"""
